[devshell]
name = "Conversations2nix"

startup.main.text = "cd nix"

[android]
toolsVersion = "26.1.1"
platformToolsVersion = "31.0.3"
buildToolsVersions = [ "30.0.2", "31.0.0" ]
platformVersions = [ "29" ]
abiVersions = [ "armeabi-v7a", "arm64-v8a" ]
